<a href="https://colab.research.google.com/github/a23308052690602-beep/Unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy es una libreria de python.
numpy se utiliza para trabajar con matrices o arreglos.
numpy es la abreviatura de "python numerico".
tambien tiene funciones para trabajar en el dominio del algebra lineal, la transformada y las matrices
en python tenemos listas que sirven como matrices pero son lentas de procesar. numpy tiene como objetivo proporcionar un objeto de matriz que sea 50 veces mas rapido que las listas tradicionales.

In [1]:
#primero tenemos que importar la libreria
import numpy

arreglo=numpy.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


numpy como np.
numpy gerenalmente se importa bajo el alias np. en python los alias son un nombre alternativo para referirce a la misma cosa.

In [2]:
import numpy as np

arreglo = np.array([6,7,8,9,10])
print(arreglo)

[ 6  7  8  9 10]


comprobando la version de numpy. la cadena de la vercion se almacena en el atributo _version_

In [3]:
import numpy as np

print(np.__version__)

2.0.2


numpy creando matrices. crear un objeto de numpy. numpy se utiliza para trabajar con matrices. el objeto de matriz se llama ndarray. podemos crear un numpy ndarray utilizando la funcion array()

In [4]:
import numpy as np

arreglo=np.array(["evelyn", "raul", "yazmin"])
print(arreglo)
print(type(arreglo))

['evelyn' 'raul' 'yazmin']
<class 'numpy.ndarray'>


dimensiones en matrices. una dimension en matrices es un nivel de profundidad de matriz (matrices anidadas) una matriz anidada contiene matrices como elemto. matrices 0-D. son elementos de una matriz. cada valor de una matriz es una matriz de 0-D. ejemplo: crea una matriz 0-D con valor de 42.

In [5]:
import numpy as np

arreglo=np.array(42)
print(arreglo)


42


matrices 1-D una matriz que tiene matrices 0-D como elementos se denomina matriz unidemensional o 1-D. estas son las matrices mas comunes y basicas. ejemplo:crea una matriz de 1-D que tenga los valores 1,2,3,4,5

In [6]:
import numpy as np

arreglo=np.array([1,2,3,4,5])

print(arreglo)


[1 2 3 4 5]


matrices de 2D. una matriz que tiene matrices 1-D como elementos se denomina matriz 2-D. a menudo se utilizan parz representar matrices de segundo orden. numpy tiene un submodulo completo dedicado a operaciones con matrices llamado numpy.mat. ejemplo:crea una matriz de 2D que contenga dos matrices con los valores 123 y 456.

In [7]:
import numpy as np

arreglo=np.array([[1,2,3],[4,5,6]])

print(arreglo)

[[1 2 3]
 [4 5 6]]


matrices 3D. una matriz que tiene matrices 2D se denomina matriz 3D. estas matrices se utilizan para representar una matriz de tercer orden. ejemplo:crea una matriz 3D con dos matrices bidimensionales, ambas conteniendo dos matrices con los valores 1,2,3 y 4,5,6.

In [9]:
import numpy as np
arreglo=np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
print(arreglo)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
