<a href="https://colab.research.google.com/github/a23308052690602-beep/Unidad1/blob/main/practica6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ana evelyn gonzalez velazquez- 24 de septiembre de 2025.
practica 6- cortar arregos numpy  
---
slice en python significa tomar elementos de un indice determinado a corto
determinado indice.
---
pasamos slice en lugar del indice de esta manera:[star:end]
sino pasamos el inicio se concidera un 0
sino pasamos el final, su longitud es conciderada una matriz de una dimension
---
ejemplo: ([1,2,3,4,5,6,7])
cortar los elementos del indice 1 al indice 5
---



In [1]:
import numpy as np
arrego=np.array([1,2,3,4,5,6,7])
print(arrego[1:5])

[2 3 4 5]


ejemplo 2:
([1,2,3,4,5,6,7])
cortar del indice 4 hasta el final de la matriz

---



In [2]:
import numpy as np
arrego=np.array([1,2,3,4,5,6,7])
print(arrego[4:])

[5 6 7]


ejemplo 3:
([1,2,3,4,5,6,7])
cortar elementos desde el principio hasta el indice 5

In [3]:
import numpy as np
arrego=np.array([1,2,3,4,5,6,7])
print(arrego[:5])

[1 2 3 4 5]


ejemplo 4:
([1,2,3,4,5,6,7])
corte negativo. utilizamos el operador "menos" para hacer referencia a un indice desde el final.
---
cortar del indice 3 desde el final al indice 1 desde el final


In [4]:
import numpy as np
arrego=np.array([1,2,3,4,5,6,7])
print(arrego[-3:-1])
#

[5 6]
